artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://data.mendeley.com/datasets/2vktdxfxv7/2
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  source_dir: artifacts/data_ingestion
  train_data_dir: artifacts/data_ingestion/train
  test_data_dir: artifacts/data_ingestion/test
