artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: # Add link to zip file e.g https://github.com/titoausten/naija-food-dataset/raw/main/pizza_steak_sushi.zip  
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
